language: python
python:
 - "3.6.4"
# command to install dependencies
install:
  - pip install -r requirement.txt
  - pip install nose
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-coverage --cover-package=app
after_success:
  - coveralls